// <auto-generated />
using FTMC.Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FTMC.Migrations
{
    [DbContext(typeof(FTMCdb))]
    partial class FTMCdbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FTMC.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .HasColumnType("VARCHAR(5)");

                    b.Property<decimal>("CustomerBudget")
                        .HasColumnType("DECIMAL(20,2)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal>("CustomerUsed")
                        .HasColumnType("DECIMAL(20,2)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("FTMC.Models.CustomerCountry", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .HasColumnType("VARCHAR(5)");

                    b.Property<string>("CountryName")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("CountryID");

                    b.ToTable("CustomerCountry");
                });
#pragma warning restore 612, 618
        }
    }
}
